"""add indexes for status and created_at

Revision ID: 7b85258ca1af
Revises: bdf42ec9a093
Create Date: 2026-08-30 16:45:41.793804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b85258ca1af'
down_revision: Union[str, Sequence[str], None] = 'bdf42ec9a093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_clips_created_at'), 'clips', ['created_at'], unique=False)
    op.create_index(op.f('ix_clips_status'), 'clips', ['status'], unique=False)
    op.create_index('ix_clips_video_id_start_time', 'clips', ['video_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_videos_created_at'), 'videos', ['created_at'], unique=False)
    op.create_index(op.f('ix_videos_status'), 'videos', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_status'), table_name='videos')
    op.drop_index(op.f('ix_videos_created_at'), table_name='videos')
    op.drop_index('ix_clips_video_id_start_time', table_name='clips')
    op.drop_index(op.f('ix_clips_status'), table_name='clips')
    op.drop_index(op.f('ix_clips_created_at'), table_name='clips')
    # ### end Alembic commands ###
