"""Pydantic schemas package.

Schemas are added in a later phase alongside their routers:
    - video.py -> VideoCreate, VideoResponse, ...
    - clip.py  -> ClipCreate, ClipResponse, ClipBoundariesUpdate, ...
    - dashboard.py -> DashboardStats, ActivityItem, ...
"""
